use_frameworks!

target 'ALWObliqueProgressBar_Example' do
  pod 'ALWObliqueProgressBar', :path => '../'

  target 'ALWObliqueProgressBar_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
